/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ClusterConfig {
  nodes: Array<string>
}
export type ScyllaCluster = Cluster
export class Cluster {
  /**
   * Object config is in the format:
   * {
   *     nodes: Array<string>,
   * }
   */
  constructor(objectConfig: ClusterConfig)
  /** Connect to the cluster */
  connect(keyspace?: string | undefined | null): Promise<ScyllaSession>
}
export class ScyllaSession {
  execute(query: string, parameters?: Array<number | string | Uuid> | undefined | null): Promise<any>
}
export class Uuid {
  /** Generates a random UUID v4. */
  static randomV4(): Uuid
  /** Parses a UUID from a string. It may fail if the string is not a valid UUID. */
  static fromString(str: string): Uuid
  /** Returns the string representation of the UUID. */
  toString(): string
}
